module.exports = {
    docs: [
        {
            type: 'doc',
            id: 'index',
        },
        {
            'go-storage': [
                {
                    type: 'autogenerated',
                    dirName: 'go-storage',
                }
            ]
        }
    ]
};
