module.exports = {
    docs: [
        {
            type: 'doc',
            id: 'index',
        },
        {
            'go-storage': [
                {
                    type: 'autogenerated',
                    dirName: 'go-storage',
                }
            ],
            'BeyondTP': [
                {
                    type: 'autogenerated',
                    dirName: 'BeyondTP',
                }
            ],
            'BeyondFS': [
                {
                    type: 'autogenerated',
                    dirName: 'BeyondFS',
                }
            ],
            'BeyondFTP': [
                {
                    type: 'autogenerated',
                    dirName: 'BeyondFTP',
                }
            ]
        }
    ]
};
